spring:

  datasource:
    url: jdbc:h2:mem:maindb

  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
      schema-locations: classpath:schema.sql

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    show-sql: true
    properties:
      hibernate:
        format_sql: false

    # WARN JpaBaseConfiguration$JpaWebConfiguration : spring.jpa.open-in-view is enabled by default.
    # Therefore, database queries may be performed during view rendering.
    # Explicitly configure spring.jpa.open-in-view to disable this warning
    open-in-view: false

  jmx:
    enabled: true

resilience4j.rateLimiter:
  configs:
    default:
      timeoutDuration: 2s
      limitRefreshPeriod: 60s
      limitForPeriod: 2


logging:
  level:
    root: info
    ru.otus.hw: debug

management:
  endpoints:
    web:
      exposure:
        include: health, metrics
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true
