logging.level.root: debug

server.port: 8080
base-url: http://localhost:${server.port}


spring:

  datasource:
    url: jdbc:h2:mem:maindb

  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
      schema-locations: classpath:schema.sql

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    show-sql: true
    properties:
      hibernate:
        format_sql: false

  security:
    oauth2:
      client:
        registration:

          # from https://github.com/settings/applications/2592046
          github:
            clientId: Ov23lisbRU56eeMfrsLp
            clientSecret: bdc0bff5c2a637c6c1d8b621431d49f57cb96c89

          # from https://oauth.yandex.ru/client/6bf668cf8fe543b8a2df44bf5078217f
          yandex:
            provider: yandex
            client-name: Yandex
            client-id: 6bf668cf8fe543b8a2df44bf5078217f
            client-secret: 9096ab5d330041c496c4fbc9dbeefd50
            redirect-uri: ${base-url}/login/oauth2/code/yandex
            authorization-grant-type: authorization_code
            scope:
              - login:email
              - login:info
        provider:
          yandex:
            authorization-uri: https://oauth.yandex.ru/authorize
            token-uri: https://oauth.yandex.ru/token
            user-name-attribute: default_email
            user-info-uri: https://login.yandex.ru/info
